### ISSUE TITLE
Administrative Review

### ISSUE THREAD

**Issue by acpaquette** [jlaura/planetary-sdi#4]
Related to #3 and #1 

- No PII

- One absolute file path found here:
https://github.com/jlaura/planetary-sdi/blob/ae53183d6f8cc6209d314174897627fd09549582/make_json_bib.sh#L3

- No internal server host names or IP addresses

- No Usernames/Passwords

**Comment by jlaura** [comment]
Can we get this as a response to #3 and #1 - this is not an issue to be fixed, but a comment on those issues. I'll get a PR open to address the absolute path issue.
